s="CGGTCTGTGGAAATATAATAGGCTCCTCCTATAAATGCGGCGACTAACGCACGTGAAGAACATCATTGTAAGAGGCTGACCCTACGGAGGCCGCCCTCGGGTGATCGCCTAGACGTGCGAGATGCCAAGGAGGGGATCGATGAAGTATCCTCTAGCAGACGACTCACATCGACCCCATAAACGAGGAGCGCGGAGGCCGGAGTACTATACAATTCTCAAACGCAATACGTCGCTAGGATCGAATCCTTGTTTTAGCACAGCCGCCGGGCCGATATCGGCTATTTAGGCTTCGTCATCCTCGCTAGGTCCCCTACGAATAGATGGTAAGTGCTTTTTCGGGCAAGACGCATAAGAAATGCGGTAGCTGAACCTACACGATACGAGCAGACGCTTCGACGTATGCATCGGCCAGGGTCCTTACTTCTATCCCGCGGATTACTTTCTTCGGGCACATATTCACTCATCGTTTAGCACTGTCTAGCCGATGATCCAGGCTCTACGAAGCCGCATGCTTGCGAACACCGTCTCGTCATCCTTGTGGCTCTTTAGGAACTAGACTAACTGAAGGGCGGAGCGTAGACAGATCTCAAATGGGTTTGCGAGCTTTCGTGAAACGTGAAATACTCTCGTGCCATGAAACCCGGGGCGGCTGCTAAGCAAAAAACAGTTCCTAATTCCTCGTTCGTTCAATAACTAACGTTTTCGCGACCTATGCGGAATCTGACATCTGCCCACCTGTTGATCAACATGGATCGCACCACTTGAGCATAGTCCGGGGTAGACCATACGTTTCTAAGTTAGTTGCTTCGACAGCGGC"

s=s[::-1]
u=""
for l in s:
    if l=="A":
        u=u+"T"
    if l=="T":
        u=u+"A"
    if l=="C":
        u=u+"G"
    if l=="G":
        u=u+"C"
        
        
        
print(u)